spring.application.name=employee-microservice-pattern

spring.datasource.url=jdbc:mysql://localhost:3306/employee_service
spring.datasource.username=root
spring.datasource.password=Ashu

spring.jpa.hibernate.ddl-auto=update

server.port=2000